### PR TITLE
Code for the instrumentation for  the assignments

### PR DESCRIPTION
**Pull request by ClintonCao**
This PR contains code that Sicco has written for instrumenting RERS problems for the assignments.

If there's anything that is missing or that I need to change, please let me know!

### CODE REVIEW

**Comment by apanichella** [comment]
Hi @ClintonCao, can you please also update the README file?

**Comment by ClintonCao** [comment]
@apanichella Yes, will do!

**Comment by apanichella** [comment]
@ClintonCao Is it all ready for the merge?

**Comment by ClintonCao** [comment]
@apanichella Yes it is ready for merge! I have updated the README and added the instrumentation code for the third assignment!

**Pull request merged**
