### PR TITLE
Fix issue with assign where z3var was passed directly instead of the …

### PR DESCRIPTION
**Pull request by TCatshoek**
…corresponding MyVar

Hi Annibale, 
We fixed a small issue in the assign function which made it impossible to modify the variables z3var. We now pass the MyVar instead of it's corresponding z3var directly, so it can be reassigned in the MyVar.

### CODE REVIEW

**Comment by apanichella** [comment]
@TCatshoek can you also add some test cases? Just to be sure we won't introduce this error in the future.

**Comment by TCatshoek** [comment]
I am not sure what would be the best way to test this since we are just checking if the methods can be called with the right type of arguments. Also, when set up like this the test will need to be pointed to the libz3java file. Maybe we should use mocking instead?  If you tell me what you think the best approach is I will try to fix it.

**Comment by apanichella** [comment]
Hi the test case looks good but we need to add assertions (unless I am overlooking  at things). As for examples of assertions, you can look at the test cases already available in the repo.

**Comment by TCatshoek** [comment]
Ok, I left out the assertions because the tests would automatically fail if the methods were called with the wrong arguments. It is probably nicer to explicitly state the assertions though. I will see if I can get maven to stop complaining about libz3java, right now it fails to run the tests because of it.

**Comment by TCatshoek** [comment]
I removed the problematic test for now since the assignment needs to be published soon and I did not find a way to mock this since we are testing the PathTracker which directly imports z3. It would need some refactoring first to allow us to mock out z3 I think. Maybe a todo for next year?

**Pull request merged**
